name: ðŸš€ CI - Build & Push Frontend

on:
  push:
    paths:
      - "travel/**"
      - "Dockerfile-frontend"
      - ".github/workflows/frontend-ci.yml"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Frontend Image
        run: |
          cd travel
          docker build -f Dockerfile-frontend -t wanderlyfs .

      - name: Tag Image
        run: |
          docker tag wanderlyfs:latest vkvaishnavi10/wanderlyfs:latest

      - name: Push Image to DockerHub
        run: |
          docker push vkvaishnavi10/wanderlyfs:latest
